"""分支名、提交信息、PR 标题与描述的格式(protocol/git.md)，纯函数加一次只读的约定识别。

格式怎么确定(每项记下来源)：
1. settings 中缺省层之上(本机或工作区)写明的 `git.branch`、`git.commit`、`git.prTemplate`(接入时经确认的历史推断也写在这里)；
2. 项目仓库写明的约定：PR 模板文件；commitlint 继承 config-conventional；CONTRIBUTING、AGENTS、CLAUDE.md 中
   同一行写了分支(或提交)并在反引号中给出带占位符的模板，占位符全部认得出、全部文档只有一个不同模板时才采用；
3. 通用格式(settings/defaults.json 的 `git` 段)。
从历史推断(infer)只给出结果交接入时确认，不自动采用。

格式串的占位符：分支 `{prefix}`(个人前缀，带结尾的 /，没有时为空)、`{type}`、`{issue}`(不补零的编号)、`{slug}`；
提交 `{type}`、`{scope}`(带括号，没有范围时为空)、`{summary}`；PR 标题 `{type}`、`{summary}`。
不带 AI 署名：提交信息完全由程序按格式串拼出，不加 Co-Authored-By、Generated with 之类的行；个人前缀不能是 AI 或工具名。
"""

from __future__ import annotations

import json
import re
from collections import Counter
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

from tightrein.settings.load import Settings

if TYPE_CHECKING:
    from tightrein.protocol.git.git import Git

BRANCH_PLACEHOLDERS = ("prefix", "type", "issue", "slug")
COMMIT_PLACEHOLDERS = ("type", "scope", "summary")
TITLE_PLACEHOLDERS = ("type", "summary")
CONVENTIONAL_COMMIT = "{type}{scope}: {summary}"
HOTFIX = "hotfix"
SETTINGS, PROJECT, GENERIC = "settings", "project", "generic"
# 个人前缀与署名里不能出现的 AI 与工具名称(小写比较)
AI_NAMES = frozenset({"ai", "agent", "bot", "claude", "anthropic", "codex", "openai", "gpt", "gemini", "agy",
                      "antigravity", "copilot", "cursor"})
ATTRIBUTION_TRAILER = "co-authored-by:"
ATTRIBUTION_PHRASES = ("generated with", "generated by", "🤖")
TEMPLATE_FILES = (".github/PULL_REQUEST_TEMPLATE.md", ".github/pull_request_template.md",
                  "docs/PULL_REQUEST_TEMPLATE.md", "docs/pull_request_template.md", "PULL_REQUEST_TEMPLATE.md",
                  "pull_request_template.md", ".gitlab/merge_request_templates/Default.md",
                  ".bitbucket/PULL_REQUEST_TEMPLATE.md")
COMMITLINT_FILES = ("commitlint.config.js", "commitlint.config.cjs", "commitlint.config.mjs", "commitlint.config.ts",
                    ".commitlintrc", ".commitlintrc.json", ".commitlintrc.yaml", ".commitlintrc.yml",
                    ".commitlintrc.js", ".commitlintrc.cjs")
CONVENTIONAL = "config-conventional"
DOC_FILES = ("CONTRIBUTING.md", ".github/CONTRIBUTING.md", "docs/CONTRIBUTING.md", "AGENTS.md", "CLAUDE.md")
BRANCH_WORDS = ("分支", "branch", "ブランチ")
COMMIT_WORDS = ("提交", "commit", "コミット")
# 文档模板中的占位符名称 → 格式字段(小写比较，含其中任一词即可)
BRANCH_NAMES = (("prefix", ("prefix", "前缀", "user", "用户", "姓名", "名前")),
                ("issue", ("issue", "编号", "number", "id", "ticket", "工单", "番号")),
                ("type", ("type", "类型", "kind", "種別", "タイプ")),
                ("slug", ("desc", "描述", "简述", "slug", "summary", "主题", "名称", "説明", "概要", "topic")))
COMMIT_NAMES = (("scope", ("scope", "范围", "模块", "module", "スコープ")),
                ("type", ("type", "类型", "種別", "タイプ")),
                ("summary", ("subject", "summary", "description", "desc", "描述", "简述", "说明", "一句话", "概要",
                             "説明", "message")))
# 从历史推断：读最近的提交数、少于多少样本不推断、统一到多少比例才算有统一风格
SAMPLE_SIZE = 50
MIN_SAMPLES = 10
MIN_RATIO = 0.8
SAMPLES_SHOWN = 5
TYPES = "feat|fix|feature|bugfix|hotfix|chore|refactor|docs"
MAIN_BRANCHES = frozenset({"main", "master", "develop", "dev", "HEAD"})
BRANCH_SHAPES = (
    ("{prefix}{type}/{issue}-{slug}", re.compile(r"^[a-z0-9]+/[a-z]+/\d+-[a-z0-9-]+$")),
    ("{prefix}{type}/{slug}", re.compile(r"^[a-z0-9]+/[a-z]+/[a-z0-9-]+$")),
    ("{prefix}{type}/{issue}-{slug}", re.compile(r"^[a-z]+/\d+-[a-z0-9-]+$")),
    ("{prefix}{type}-{slug}", re.compile(rf"^[a-z0-9]+/(?:{TYPES})-[a-z0-9-]+$")),
    ("{prefix}{type}/{slug}", re.compile(rf"^(?:{TYPES})/[a-z0-9-]+$")),
)
# PR 模板的标题按关键词归到内容(小写比较，先命中先用)
TEMPLATE_KEYS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("verification", ("test", "verif", "测试", "验证", "テスト", "検証")),
    ("relations", ("related", "issue", "link", "关联", "相关", "関連")),
    ("limitations", ("limitation", "risk", "caveat", "known", "局限", "风险", "不足", "注意", "制限", "リスク")),
    ("approach", ("why", "approach", "how", "implementation", "solution", "change", "方案", "实现", "做法", "改动", "変更",
                  "実装")),
    ("problem", ("problem", "summary", "description", "what", "background", "context", "motivation", "问题", "背景",
                 "概要", "概括", "描述", "目的")),
)
PROSE = ("problem", "approach", "limitations")
_PLACEHOLDER = re.compile(r"\{(\w+)\}")
_SEGMENT = r"[a-z0-9]+(?:-[a-z0-9]+)*"
_CODE = re.compile(r"`([^`\n]+)`")
_DOC_PLACEHOLDER = re.compile(r"<([^<>]+)>|\{([^{}]+)\}")
_CONVENTIONAL_SUBJECT = re.compile(r"^[a-z]+(\([^)]+\))?!?: \S")
_TEMPLATE_HEADING = re.compile(r"^(#{1,3}) +(.+?)[ \t]*$", re.MULTILINE)
_COMMENT = re.compile(r"<!--.*?-->", re.DOTALL)
_WORD = re.compile(r"[a-z0-9]+")


class FormatError(ValueError):
    """格式串含有不认识的占位符。"""


class BranchRejected(ValueError):
    """项目要求个人前缀而没有配置，或前缀是 AI 或工具名称。"""


@dataclass(frozen=True)
class Conventions:
    branch: str
    commit: str
    title: str
    template: str | None
    prefix: str  # 本机配置的个人前缀，没有时为空
    personal_prefix: bool
    types: Mapping[str, str]  # Issue 种类(bug、feature) → 分支与提交的类型
    sources: Mapping[str, str] = field(default_factory=dict)  # branch、commit、template → 来源与出处

    @property
    def branch_pattern(self) -> re.Pattern[str]:
        return branch_pattern(self.branch)


@dataclass(frozen=True)
class PullText:
    """PR 描述的内容：正文三段、关联与程序生成的验证结果；缺少的段落为空。"""

    problem: str
    approach: str
    limitations: str
    relations: tuple[str, ...]
    verification: tuple[str, ...]


@dataclass(frozen=True)
class Inferred:
    format: str | None  # 没有统一风格时为空
    ratio: float
    samples: tuple[str, ...]


@dataclass(frozen=True)
class Inference:
    """从最近的提交与远程分支名推断出的风格，交接入时确认后写进工作区 settings 的 git 段。"""

    commit: Inferred
    branch: Inferred


# 格式串


def check_format(text: str, allowed: Sequence[str]) -> None:
    unknown = sorted(set(_PLACEHOLDER.findall(text)) - set(allowed))
    if unknown:
        raise FormatError(f"格式 {text} 含有不认识的占位符：{'、'.join(unknown)}；可用 {'、'.join(allowed)}")


def kebab(text: str) -> str:
    """小写、非字母数字换成短横线、去掉首尾与重复的短横线。"""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def branch_type(kind: str, *, urgent: bool, types: Mapping[str, str]) -> str:
    """立即修的 P0 为 hotfix，其余按 Issue 种类映射。"""
    return HOTFIX if urgent else types[kind]


def branch(fmt: str, *, kind: str, issue: str, slug: str, prefix: str | None = None) -> str:
    check_format(fmt, BRANCH_PLACEHOLDERS)
    number = issue.lstrip("0") or "0"
    return fmt.format(prefix=f"{prefix}/" if prefix else "", type=kind, issue=number, slug=kebab(slug))


def branch_pattern(fmt: str) -> re.Pattern[str]:
    """符合分支格式的分支名(类型与描述为小写短横线词，编号为数字，个人前缀可有可无)。"""
    check_format(fmt, BRANCH_PLACEHOLDERS)
    parts = {"prefix": rf"(?:{_SEGMENT}/)?", "type": _SEGMENT, "issue": r"\d+", "slug": _SEGMENT}
    regex = "".join(parts[piece] if index % 2 else re.escape(piece)
                    for index, piece in enumerate(_PLACEHOLDER.split(fmt)))
    return re.compile(rf"^{regex}$")


def prefix_forbidden(prefix: str) -> bool:
    return prefix.lower() in AI_NAMES


def branch_name(conventions: Conventions, *, kind: str, issue: str, slug: str) -> str:
    if conventions.personal_prefix:
        if not conventions.prefix:
            raise BranchRejected("本项目的分支名要求个人前缀，先在本机 settings/controls.json 设置 git.branchPrefix")
        if prefix_forbidden(conventions.prefix):
            raise BranchRejected(f"分支前缀不能使用 AI 或工具名称：{conventions.prefix}")
    prefix = conventions.prefix if conventions.personal_prefix else None
    return branch(conventions.branch, kind=kind, issue=issue, slug=slug, prefix=prefix)


def branch_problem(name: str, conventions: Conventions) -> str | None:
    """已有分支名的问题：不符合格式，或个人前缀是 AI 或工具名称；没有问题时为 None。"""
    if conventions.branch_pattern.fullmatch(name) is None:
        return f"分支名 {name} 不符合本项目的分支格式 {conventions.branch}"
    prefix = name.split("/", 1)[0]
    if conventions.personal_prefix and prefix_forbidden(prefix):
        return f"分支前缀 {prefix} 是 AI 或工具名称"
    return None


def commit_message(fmt: str, *, kind: str, scope: str | None, summary: str, why: str | None) -> str:
    """第一行按格式串，空一行后写为什么这样改；不加任何署名行。"""
    check_format(fmt, COMMIT_PLACEHOLDERS)
    first = fmt.format(type=kind, scope=f"({scope})" if scope else "", summary=summary.strip())
    return first + (f"\n\n{why.strip()}" if why and why.strip() else "") + "\n"


def title(fmt: str, *, kind: str, summary: str) -> str:
    check_format(fmt, TITLE_PLACEHOLDERS)
    return fmt.format(type=kind, summary=summary.strip())


def attribution_lines(message: str) -> list[str]:
    """提交信息或 PR 描述中的 AI 署名行：提到 AI 或工具名称的 Co-Authored-By，以及 Generated with 之类的行。"""
    found = []
    for line in message.splitlines():
        lowered = line.strip().lower()
        trailer = lowered.startswith(ATTRIBUTION_TRAILER) and bool(AI_NAMES & set(_WORD.findall(lowered)))
        if trailer or any(phrase in lowered for phrase in ATTRIBUTION_PHRASES):
            found.append(line)
    return found


# PR 描述


def pull_body(text: PullText, verification_title: str) -> str:
    """通用的 PR 描述，不分固定小节：问题、做法、局限三段，之后是关联，最后是程序生成的验证结果。"""
    parts = [part.strip() for part in (text.problem, text.approach, text.limitations) if part.strip()]
    if text.relations:
        parts.append("\n".join(text.relations))
    if text.verification:
        parts.append(f"---\n\n{verification_title}\n\n{_bullets(text.verification)}")
    return "\n\n".join(parts) + "\n"


def fill_template(template: str, text: PullText, verification_title: str) -> str:
    """按项目 PR 模板的标题放进同样的内容：认得出的标题下的注释与空白由内容取代，模板原有的复选框保留；认不出的
    标题保留模板原文；模板没有对应标题的内容附在后面不丢；一个标题都认不出时在模板之后附上通用描述。"""
    contents = {"problem": text.problem.strip(), "approach": text.approach.strip(),
                "limitations": text.limitations.strip(), "relations": "\n".join(text.relations),
                "verification": _bullets(text.verification)}
    matches = list(_TEMPLATE_HEADING.finditer(template))
    if all(_template_key(match.group(2)) is None for match in matches):
        return template.rstrip() + "\n\n" + pull_body(text, verification_title)
    present = {_template_key(match.group(2)) for match in matches}
    prose = [key for key in PROSE if key in present]
    if prose:
        # 模板没有对应标题的正文段落并入第一个正文标题之下
        extra = [contents[key] for key in PROSE if key not in present and contents[key]]
        contents[prose[0]] = "\n\n".join(part for part in (contents[prose[0]], *extra) if part)
    used: set[str] = set()
    parts = [template[:matches[0].start()].rstrip()]
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(template)
        original = template[match.end():end].strip()
        key = _template_key(match.group(2))
        if key is None or key in used:
            parts.append(f"{match.group(0)}\n\n{original}".rstrip())
            continue
        used.add(key)
        kept = _COMMENT.sub("", original).strip()
        body = contents[key] or kept
        if kept and kept != body and "- [" in kept:
            body = f"{body}\n\n{kept}"
        parts.append(f"{match.group(0)}\n\n{body}".rstrip())
    tail = [contents["relations"]] if "relations" not in used and contents["relations"] else []
    if "verification" not in used and contents["verification"]:
        tail.append(f"---\n\n{verification_title}\n\n{contents['verification']}")
    return "\n\n".join(part for part in [*parts, *tail] if part) + "\n"


# 识别与推断


def resolve(settings: Settings, repo: Path) -> Conventions:
    """按优先级取本项目的格式；sources 写明每一项的来源，供 PR 与运行摘要说明。"""
    sources: dict[str, str] = {}
    branch_format = _configured(settings, "git.branch")
    if branch_format is not None:
        sources["branch"] = SETTINGS
    else:
        found = _doc_template(repo, BRANCH_WORDS, BRANCH_NAMES, BRANCH_PLACEHOLDERS, "slug")
        branch_format, sources["branch"] = (found[0], f"{PROJECT}:{found[1]}") if found \
            else (settings.get("git.branch"), GENERIC)
    commit_format = _configured(settings, "git.commit")
    if commit_format is not None:
        sources["commit"] = SETTINGS
    else:
        found = _doc_template(repo, COMMIT_WORDS, COMMIT_NAMES, COMMIT_PLACEHOLDERS, "summary")
        linted = _commitlint(repo)
        if found:
            commit_format, sources["commit"] = found[0], f"{PROJECT}:{found[1]}"
        elif linted:
            commit_format, sources["commit"] = CONVENTIONAL_COMMIT, f"{PROJECT}:{linted}"
        else:
            commit_format, sources["commit"] = settings.get("git.commit"), GENERIC
    template_path = _configured(settings, "git.prTemplate")
    template = _read(repo, template_path) if template_path else None
    if template is not None:
        sources["template"] = f"{SETTINGS}:{template_path}"
    else:
        name = next((item for item in TEMPLATE_FILES if _is_file_exactly(repo, item)), None)
        template = _read(repo, name) if name else None
        sources["template"] = f"{PROJECT}:{name}" if name else GENERIC
    check_format(branch_format, BRANCH_PLACEHOLDERS)
    check_format(commit_format, COMMIT_PLACEHOLDERS)
    prefix = str(settings.get("git.branchPrefix") or "")
    required = sources["branch"] != GENERIC and "{prefix}" in branch_format
    return Conventions(branch_format, commit_format, settings.get("git.pr"), template, prefix,
                       bool(prefix) or required, dict(settings.get("git.types")), sources)


def infer(subjects: Sequence[str], branches: Sequence[str], *, min_ratio: float = MIN_RATIO,
          min_samples: int = MIN_SAMPLES) -> Inference:
    """提交：Conventional Commits 的比例达到 min_ratio 时为该格式。分支：最常见的形状达到比例时为它的格式。
    去掉 Merge 提交与主分支名；样本少于 min_samples 时不推断。"""
    commits = [subject for subject in subjects if subject and not subject.startswith("Merge ")]
    matched = [subject for subject in commits if _CONVENTIONAL_SUBJECT.match(subject)]
    ratio = len(matched) / len(commits) if commits else 0.0
    commit_format = CONVENTIONAL_COMMIT if len(commits) >= min_samples and ratio >= min_ratio else None
    named = [name for name in branches if name not in MAIN_BRANCHES]
    shapes: Counter[str] = Counter()
    examples: dict[str, list[str]] = {}
    for name in named:
        shape = next((fmt for fmt, pattern in BRANCH_SHAPES if pattern.match(name)), None)
        if shape is not None:
            shapes[shape] += 1
            examples.setdefault(shape, []).append(name)
    branch_format, share = None, 0.0
    shown: tuple[str, ...] = ()
    if shapes:
        best, count = shapes.most_common(1)[0]
        share = count / len(named)
        shown = tuple(examples[best][:SAMPLES_SHOWN])
        if len(named) >= min_samples and share >= min_ratio:
            branch_format = best
    return Inference(Inferred(commit_format, ratio, tuple(matched[:SAMPLES_SHOWN])),
                     Inferred(branch_format, share, shown))


def infer_from_repo(git: Git) -> Inference:
    """读最近 SAMPLE_SIZE 条提交与全部远程分支名后推断(只读)。"""
    return infer([commit.subject for commit in git.log("HEAD", limit=SAMPLE_SIZE)], git.remote_branches())


# 内部函数


def _bullets(items: Sequence[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def _template_key(heading: str) -> str | None:
    lowered = heading.lower()
    return next((key for key, words in TEMPLATE_KEYS if any(word in lowered for word in words)), None)


def _configured(settings: Settings, key: str) -> str | None:
    """缺省层之上(本机或工作区)写明的取值；只有缺省值时为 None。"""
    defaults = settings.layers[0].name if settings.layers else None
    found = [value for layer, value in settings.explain(key) if layer != defaults and value]
    return str(found[-1]) if found else None


def _read(repo: Path, name: str) -> str | None:
    path = repo / name
    return path.read_text(encoding="utf-8", errors="replace") if path.is_file() else None


def _is_file_exactly(repo: Path, name: str) -> bool:
    """文件存在且路径各段的大小写与 name 一致：大小写不敏感的文件系统上 is_file 对大小写不同的名字也为真，
    按候选顺序取第一个时会把 pull_request_template.md 记成 PULL_REQUEST_TEMPLATE.md。"""
    if not (repo / name).is_file():
        return False
    parent = repo
    for part in Path(name).parts:
        if part not in {child.name for child in parent.iterdir()}:
            return False
        parent = parent / part
    return True


def _convert(text: str, names: Sequence[tuple[str, Sequence[str]]], allowed: Sequence[str]) -> str | None:
    """把文档中的模板(如 `<类型>/<编号>-<简述>`)换成格式串；有认不出的占位符时为 None。"""
    failed = False

    def field_of(match: re.Match[str]) -> str:
        nonlocal failed
        word = (match.group(1) or match.group(2)).strip().lower()
        found = next((key for key, words in names if any(item in word for item in words)), None)
        if found is None or found not in allowed:
            failed = True
            return ""
        return "{" + found + "}"

    converted = _DOC_PLACEHOLDER.sub(field_of, text.strip())
    if failed or not _DOC_PLACEHOLDER.search(text):
        return None
    return converted.replace("{prefix}/", "{prefix}").replace("({scope})", "{scope}")


def _doc_template(repo: Path, words: Sequence[str], names: Sequence[tuple[str, Sequence[str]]],
                  allowed: Sequence[str], required: str) -> tuple[str, str] | None:
    """各说明文档中关于分支(或提交)的模板；全部文档只有一个不同的模板时返回 (格式串, 出处)，拿不准就不采用。"""
    found: dict[str, str] = {}
    for name in DOC_FILES:
        text = _read(repo, name)
        if text is None:
            continue
        for number, line in enumerate(text.splitlines(), start=1):
            if not any(word in line.lower() for word in words):
                continue
            for code in _CODE.findall(line):
                converted = _convert(code, names, allowed)
                if converted is not None and "{" + required + "}" in converted:
                    found.setdefault(converted, f"{name}:{number}")
    if len(found) != 1:
        return None
    return next(iter(found.items()))


def _commitlint(repo: Path) -> str | None:
    for name in COMMITLINT_FILES:
        text = _read(repo, name)
        if text is not None and CONVENTIONAL in text:
            return name
    package = _read(repo, "package.json")
    if package is None:
        return None
    try:
        data = json.loads(package)
    except ValueError:
        return None
    return "package.json" if CONVENTIONAL in json.dumps(data.get("commitlint") or {}) else None
